theme: jekyll-theme-leap-day
url: https://shoque2.github.io
baseurl: /personal-web/

# Site settings
title: Hello. I am Sharia Hoque
email: shariahoque20@gmail.com
description: "I will write here later"

# Team names, titles and social links
people:
- name: Sharia Hoque
  pic: 1
  position: Undergraduate

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Linkedin 
    url: https://www.linkedin.com/in/sharia-hoque/
  - title: github
    url: https://github.com/shariahoque01

# Postal address (add as many lines as necessary)
address:
  - line: Queens, NY 11433

# Build settings
markdown: kramdown
permalink: pretty
